### ISSUE TITLE
Add support for JavaScript

### ISSUE THREAD

**Issue by MyHwu9508** [LemonUIbyLemon/LemonUI_TS#1]
Howdy!

I already requested this feature on Discord, but however listed here is better trackable.

As written in the title, sadly LemonUI is not available for JS. Since NativeUI is no longer maintained and the guy who ported it to alt:V also stopped working on that, migrating to Lemon UI would be just great. 

My NativeUI version had no update since 2019 and has some minor performance issues & missing features.

Thank you! <3

**Comment by justalemon** [comment]
This is the new repo for the JS/TS version of LemonUI. It will take a couple of months to have feature parity with the .NET version of LemonUI but it will be done.
